# Buildspec file for AWS CodeBuild

version: 0.2

phases:
  pre_build:
    commands:
      - echo Login in to Amazon Elastic Container Registry...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 590183699263.dkr.ecr.eu-west-1.amazonaws.com

  build:
    commands:
      - echo Starting Build Phase...
      - echo Build started on `date`
      - echo Building the Docker Image...
      # Command to build docker i
      - docker build -t mlops-repository-aws .
      # Tagging image to push it to the repository
      - docker tag mlops-repository-aws:latest 590183699263.dkr.ecr.eu-west-1.amazonaws.com/mlops-repository-aws:new1

  post_build:
    commands:
      - echo Starting Post-Build Phase...
      - echo Build completed on `date`
      - echo Pushing the latest docker image
      - docker push 590183699263.dkr.ecr.eu-west-1.amazonaws.com/mlops-repository-aws:new1
      # Creating artifact for ECS deployment
      - echo '[{"name":"flask-container","imageUri":"590183699263.dkr.ecr.eu-west-1.amazonaws.com/mlops-repository-aws:latest"}]' > imagedefinitions.json
      
artifacts:
  files: imagedefinitions.json